### ISSUE TITLE
should not depend on Dist::Zilla::Plugin::ReadmeFromPod

### ISSUE THREAD

**Issue by chorny** [NatLibFi/MARC-File-MARCXML#1]
Modules that are used when creating distribution should only be required on author perl.

**Comment by ghost** [comment]
Thanks for the heads up.

I agree that build (BuildRequires) is the wrong phase for the dependency. **DevelopRequires** should be used instead. According to [CPAN::Meta::Spec](http://search.cpan.org/perldoc?CPAN%3A%3AMeta%3A%3ASpec#PREREQUISITES) **develop** phase should be used for dependencies that are required for distribution creation:

```
develop

    The develop phase's prereqs are libraries needed to work on the distribution's source code as its author does. These tools might be needed to build a release tarball, to run author-only tests, or to perform other tasks related to developing new versions of the distribution.
```

**Comment by ghost** [comment]
Moved to DevelopRequires in f8b3925b8adf879560396e8a4d0abfb6a69fb0ca.
