### ISSUE TITLE
Deal with multiple records per file

### ISSUE THREAD

**Issue by powerriegel** [NatLibFi/MARC-File-MARCXML#2]
Hello, 
I'm using your module to convert MARCXML files into Pica+. 
I'm using this format: https://www.loc.gov/standards/marcxml/xml/collection.xml
(removed the namespaces according to your code).

The result is one MARC::Record object which contains all fields from all records in the MARCXML file. 

It seems multiple records per file (a collection) are not recognized. Is it possible to add this feature? That would be quite helpful. Or how do you process such records? 

I would also make the namespace configurable and add an xpath selector option to jump into the right node for where the marc data is. What do you think? 

Regards,
Cornelius

**Comment by ghost** [comment]
Hi,
Yes, implementing both of these features is a good idea. Unfortunately we don't really maintain this library anymore but we'll be glad to accept PRs :)

**Comment by powerriegel** [comment]
Hello,
I looked into the code and tried around a lot but there seems to be no straightforward way to implement this. At least the `in()`, `_next()` and `decode()` method need to be rewritten. 

`in() `needs to do the parsing and `_next()` just iterates through the parsed records. 
I was not able to override MARC::Files in mplementation. There seems to be no real object orientation. 

That's why I can't offer a pull request.

**Comment by jorol** [comment]
MARC::File::XML supports `collections`:

```perl
#!/usr/bin/env perl

use strict;
use utf8;
use warnings;

use MARC::File::XML;
use DDP;

## Setting the record format without USE options
MARC::File::XML->default_record_format('USMARC');

## or reading with MARC::File::XML explicitly
my $file = MARC::File::XML->in( 'collection.xml' );

while (my $record = $file->next()) {
    p $record;
}
```

**Comment by powerriegel** [comment]
Thanks, that helps me a lot! I've googled around a lot but did not find this module.

**Comment by jorol** [comment]
Don't google for Perl modules, search https://metacpan.org/ ;-)
